language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1
 - 7.0

env:
 global:
  - IGNORE_PATHS=node_modules
  - MOODLE_BRANCH=MOODLE_34_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

matrix:
    include:
      - env: MOODLE_BRANCH=master DB=pgsql
    allow_failuers:
      - env: MOODLE_BRANCH=master DB=pgsql

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt -t eslint
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile chrome
